<template>
<div class="lay" v-if="isModalVisible">
    <div class="modal_side modal_right">
                <div class="modal_side_wrap">
                    <div class="modal_head modal_head_tarif">
                        <h5>Правила тарифа</h5>
                        <div class="tarif_switch tabs tabs-but">
                            <a href="#" :class="{'active': indexItem === index }" class="swit_tarif1" v-for="(item, index) in segments.PaxSegmentList.PaxSegment" @click="showSection(item.PaxSegmentID, index)" :key="index">{{ item.Dep.IATA_LocationCode }} </a>
                        </div>
                        <div class="razdel_switch tabs tabs-but">
                            <a href="#" class="swit_razdel1 active">Раздел 15</a>
                            <a href="#" class="swit_razdel2">Раздел 16</a>
                            <a href="#" class="swit_razdel3">Раздел 21</a>
                            <a href="#" class="swit_razdel4">Раздел 22</a>
                        </div>
                        <a href="#" class="btn btn-icon btn-blue_fill modal_close" @click="closeModal">
                            <svg class="icon18"><use xlink:href="./img/sprite.svg#ico_close"></use></svg>
                        </a>
                    </div>
                    <div class="rules_wrap">
                        <div class="rules_item">
                            <span v-for="(el, index) in sections" :key="index">
                                {{ el.PaxSegmentRefID }}
                                <!-- <span v-html="el.FareRuleText.Remark.RemarkText"></span>  -->
                                {{ el.FareRuleText.Remark.RemarkText }}
                            </span>
                      
                            <!-- S7 ECONOMY CLASS BASIC FARES<br>- FOR ECONOMY CLASS SERVICE <br>- FOR THE FOLLOWING TYPES OF TRANSPORTATION: ROUND-TRIP (RT), CIRCLE-TRIP (CT), OPEN-JAW (OJ)<br>NOTES. INCLUDED-<br> -CABIN BAGGAGE UP TO 10 KG PER PASSENGER<br>  NUMBER OF ITEMS IS NOT LIMITED<br>  THE TOTAL SIZE OF ALL ITEMS SHOULD NOT EXCEED<br>  118 CM/55X40X23/<br>  THE TOTAL WEIGHT OF ALL ITEMS SHOULD NOT<br>  EXCEED 10 KG<br> -MILES ACCRUAL IN ACCORDANCE WITH AIRLINE RULES<br>NOT OFFERED-<br> -FREE BAGGAGE ALLOWANCE<br> -TRAVEL KIT<br> -PRIORITY CHECK-IN<br> -PRIORITY SECURITY AND PASSPORT CONTROL<br> -PRIORITY BOARDING<br>AT CHARGE-<br> -EXTRA BAG /ALL CHECKED BAGS/<br> -SEAT SELECTION DURING SALE AT CHARGE /NOT FOR<br>  EXTRA SPACE SEAT/<br> -SEAT SELECTION DURING CHECK-IN AT THE AIRPORT<br>  AT CHARGE /NOT FOR EXTRA SPACE SEAT/<br> -EXTRA SPACE SEAT<br> -SPECIAL MEAL /IF AVAILABLE/<br> -CARRIAGE OF SKI/SNOWBOARD EQUIPMENT<br> -LOUNGE ACCESS<br> -UPGRADE TO BUSINESS WITHOUT LOUNGE ACCESS /VIA<br>  WWW.S7.RU OR DURING CHECK-IN AT THE AIRPORT/<br> -SMS NOTIFICATION<br> -TICKET REFUNDABILITY<br>NOTES. -UNACCOMPANIED CHILDREN ARE NOT ELIGIBLE.<br>-UNACCOMPANIED INFANTS ARE NOT ELIGIBLE.<br>FARE COMPONENT MUST BE NOT ON FLIGHTS С74000-С74999 <br>AND<br>FARE COMPONENT MUST BE ON FLIGHTS S7 <br>NOTES. -NOT VALID ON ANY CODE SHARE FLIGHTS WHERE S7 IS<br> A MARKETING CARRIER.<br>-SEE FARE DISPLAY FOR ROUTING INFORMATION.<br>RESERVATIONS MUST BE COMPLETED: <br>AT LEAST 4 DAY(S) BEFORE DEPARTURE<br>RESERVATIONS ARE REQUIRED FOR ALL SECTORS <br>TICKETING MUST BE COMPLETED: <br>- WITHIN 3 HOUR(S) AFTER RESERVATIONS ARE MADE <br>OR<br>RESERVATIONS ARE REQUIRED FOR ALL SECTORS <br>TICKETING MUST BE COMPLETED: <br>- WITHIN 20 MINUTE(S) AFTER RESERVATIONS ARE MADE <br>RESERVATIONS AND TICKETING MUST BE COMPLETED AT THE SAME TIME <br>NOTES. -DUE TO AUTOMATED TICKETING DEADLINE CONTROL<br> DIFFERENCE COULD EXIST BETWEEN THE FARE RULE<br> LAST TICKETING DATE AND THE SYSTEM GENERATED<br> TICKETING DEADLINE MESSAGE. THE MORE<br> RESTRICTIVE TICKETING DEADLINE APPLIES.<br>TRAVEL FROM TURNAROUND MUST COMMENCE NO LATER THAN 308 DAY(S)  AFTER DEPARTURE FROM FARE ORIGIN<br>NOT PERMITTED<br>OPEN JAWS<br>FARES MAY BE COMBINED ON A HALF ROUND TRIP BASIS TO FORM TRIPS <br>SINGLE OR DOUBLE OPEN-JAWS <br>RESTRICTIONS:<br>the length of open or surface sectors should be equal to or less than the length of the shortest portion of OJ<br>NOTES. COMBINATIONS PERMITTED ONLY WITH S7 BASIC FARES.<br>COMBINATIONS ARE NOT PERMITTED WITH ANY PLUS/<br>STANDARD/SPA/ALLIANCE FARES OR WITH FARES OF<br>ANOTHER CARRIER.<br>IN CASE OF FARES COMBINATION ON HALF ROUND TRIP<br>BASIS WITH DIFFERENT CONDITIONS<br>A - THE CONDITIONS FOR EACH SEGMENT APPLY FOR<br>CATEGORIES-<br>    2-DAY/TIME<br>    3-SEASONALITY<br>    4-FLIGHT APPLICATIONS<br>    9-TRANSFERS<br>   11-BLACKOUT DATES<br>   17-HIP AND MILEAGE EXCEPTIONS<br>   19-CHILDREN AND INFANT DISCOUNTS<br>B - FOR OTHER CATEGORIES THE MORE RESTRICTIVE<br>CONDITIONS FOR PRICING UNIT APPLY.<br><br>IF<br>WITH FARES OF S7 FOR TRAVEL FROM ANY POINT TO ANY POINT<br>AND<br>COMBINATIONS WITH FARES HAVING ONE OF FOLLOWING RULE NUMBERS *SBSC,*SBST,*SBEM,*SBSG,*SBSO,*SALE,*TINK. <br>AND<br>COMBINATIONS WITH FARES  HAVING ONE OF THE FOLLOWING FARE TYPE CODES: XAT,XAC,BXN,BXS <br>CIRCLE TRIP WITH TWO FARE COMPONENTS<br>FARES MAY BE COMBINED ON A HALF ROUND TRIP BASIS TO FORM TRIPS <br>NOTES. COMBINATIONS PERMITTED ONLY WITH S7 BASIC FARES.<br>COMBINATIONS ARE NOT PERMITTED WITH ANY PLUS/<br>STANDARD/SPA/ALLIANCE FARES OR WITH FARES OF<br>ANOTHER CARRIER.<br>IN CASE OF FARES COMBINATION ON HALF ROUND TRIP<br>BASIS WITH DIFFERENT CONDITIONS<br>A - THE CONDITIONS FOR EACH SEGMENT APPLY FOR<br>CATEGORIES-<br>    2-DAY/TIME<br>    3-SEASONALITY<br>    4-FLIGHT APPLICATIONS<br>    9-TRANSFERS<br>   11-BLACKOUT DATES<br>   17-HIP AND MILEAGE EXCEPTIONS<br>   19-CHILDREN AND INFANT DISCOUNTS<br>B - FOR OTHER CATEGORIES THE MORE RESTRICTIVE<br>CONDITIONS FOR PRICING UNIT APPLY.<br><br>IF<br>WITH FARES OF S7 FOR TRAVEL FROM ANY POINT TO ANY POINT<br>AND<br>COMBINATIONS WITH FARES HAVING ONE OF FOLLOWING RULE NUMBERS *SBSC,*SBST,*SBEM,*SBSG,*SBSO,*SALE,*TINK. <br>AND<br>COMBINATIONS WITH FARES  HAVING ONE OF THE FOLLOWING FARE TYPE CODES: XAT,XAC,BXN,BXS <br>CIRCLE TRIP WITH MORE THAN TWO FARE COMPONENTS<br>FARES MAY BE COMBINED ON A HALF ROUND TRIP BASIS<br>NOTES. COMBINATIONS PERMITTED ONLY WITH S7 BASIC FARES.<br>COMBINATIONS ARE NOT PERMITTED WITH ANY PLUS/<br>STANDARD/SPA/ALLIANCE FARES OR WITH FARES OF<br>ANOTHER CARRIER.<br>IN CASE OF FARES COMBINATION ON HALF ROUND TRIP<br>BASIS WITH DIFFERENT CONDITIONS<br>A - THE CONDITIONS FOR EACH SEGMENT APPLY FOR<br>CATEGORIES-<br>    2-DAY/TIME<br>    3-SEASONALITY<br>    4-FLIGHT APPLICATIONS<br>    9-TRANSFERS<br>   11-BLACKOUT DATES<br>   17-HIP AND MILEAGE EXCEPTIONS<br>   19-CHILDREN AND INFANT DISCOUNTS<br>B - FOR OTHER CATEGORIES THE MORE RESTRICTIVE<br>CONDITIONS FOR PRICING UNIT APPLY.<br><br>IF<br>WITH FARES OF S7 FOR TRAVEL FROM ANY POINT TO ANY POINT<br>AND<br>COMBINATIONS WITH FARES HAVING ONE OF FOLLOWING RULE NUMBERS *SBSC,*SBST,*SBEM,*SBSG,*SBSO,*SALE,*TINK. <br>AND<br>COMBINATIONS WITH FARES  HAVING ONE OF THE FOLLOWING FARE TYPE CODES: XAT,XAC,BXN,BXS <br>END-ON-END<br>END-ON-END PERMITTED <br>NOTES. COMBINATIONS PERMITTED ONLY WITH S7 BASIC FARES.<br>COMBINATIONS ARE NOT PERMITTED WITH ANY PLUS/<br>STANDARD/SPA/ALLIANCE FARES OR WITH FARES OF<br>ANOTHER CARRIER.<br><br>IF<br>WITH FARES OF S7 FOR TRAVEL FROM ANY POINT TO ANY POINT<br>AND<br>COMBINATIONS WITH FARES HAVING ONE OF FOLLOWING RULE NUMBERS *SBSC,*SBST,*SBEM,*SBSG,*SBSO,*SALE,*TINK. <br>AND<br>COMBINATIONS WITH FARES  HAVING ONE OF THE FOLLOWING FARE TYPE CODES: XAT,XAC,BXN,BXS <br>ADD-ONS<br>PERMITTED<br>- TICKETS MAY BE ISSUED <br>- VALIDATING CARRIERS:PUBLISHING CARRIER <br>ELECTRONIC TICKETING PERMITTED<br>NOTES. SALES PERMITTED ON TICKET STOCK VALIDATED OR<br>PLATED S7/421 ONLY.<br>GENERAL RULE - APPLY UNLESS OTHERWISE SPECIFIED<br>CANCELLATIONS<br>ANY TIME<br>TICKET IS NON-REFUNDABLE IN CASE OF CANCEL/NO-SHOW/REFUND<br><br>NOTES. ---THESE RULES ARE APPLIED FOR ALL REFUND<br>   METHODS INCLUDING VOUCHER/CERTIFICATE---<br>-REFUND WITHOUT CHARGES IS PERMITTED ONLY FOR<br> INFANTS WITHOUT A SEAT.<br>-RULES FOR CANCELLATION APPLY BY PRICING UNIT.<br>---<br>     -INVOLUNTARY REFUND-<br>-IN CASE OF INVOLUNTARY REFUND VOUCHER/CERTIFICATE<br> ISSUING IS NOT PERMITTED.<br>-FOR FULLY UNUSED TICKET-REFUND THE FARE PAID.<br>-FOR PARTIALLY USED TICKET - REFUND THE<br> APPLICABLE FARE ON THE REFUNDABLE SEGMENT /ONE<br> WAY OR ONE HALF RT/ IT DEPENDS ON FARE<br> CONSTRUCTION/.<br>-REFUND OF ALL UNUSED TAXES/FEES/CHARGES IS<br> PERMITTED.<br>---<br>     -IN ANY CASES-<br>-REFUNDS MUST BE MADE WITHIN 1 YEAR FROM<br>-DATE OF ISSUE - FOR UNUSED TICKETS.<br>-DATE OF DEPARTURE ON FIRST FLIGHT COUPON-<br> FOR PARTLY USED TICKETS.<br><br>IN OTHER CASES<br>CHANGES<br>ANY TIME<br>CHARGE EUR 65 FOR REISSUE/REVALIDATION<br><br>CHANGES<br>ANY TIME<br>CHANGES NOT PERMITTED IN CASE OF NO-SHOW<br><br>NOTES. -CHANGES PROVISIONS-<br>-CHANGE IS A ROUTING/DATE/FLIGHT/BOOKING<br> CLASS MODIFICATION.<br>-CHARGE APPLIES PER TRANSACTION.<br>-CHANGES PROVISIONS ARE DEFINED WITH REFERENCE TO<br> THE TIME OF TICKET CHANGES PROCESSING IN THE<br> RESERVATION SYSTEM AND DOES NOT DEPEND ON THE<br> TIME OF SEATS CANCELLATION IN PNR-<br> -IF A TICKET IS PERFORMED FOR CHANGES AT LEAST<br>  40 MINUTES BEFORE THE FLIGHT DEPARTURE THE<br>  CHARGE FOR REISSUE/REVALIDATION IS APPLIED.<br> -IF A TICKET IS PERFORMED FOR CHANGES LESS THAN<br>  40 MINUTES BEFORE THE FLIGHT DEPARTURE /NO-SHOW/<br>  CHANGES ARE NOT PERMITTED.<br>-CHILDREN DISCOUNTS ARE NOT APPLIED TO THE CHARGE.<br>-INFANTS WITHOUT A SEAT - WITHOUT CHARGE.<br>-CHARGE IS ALWAYS CONVERTED INTO THE LOCAL<br> CURRENCY USING ACTUAL SYSTEM EXCHANGE RATE ON THE<br> DATE OF REISSUE.<br>-ALL RULE PROVISIONS OF THE NEW FARE INCLUDING<br> ADVANCE PURCHASE/MIN STAY/MAX STAY/SEASONALITY/<br> ETC MUST BE MET.<br>-CHANGES MAY BE DONE ONLY WITHIN BASIC FARE<br> FAMILY. CHANGES OF THIS FARE TO ANY STANDARD OR<br> PLUS FARE IS NOT PERMITTED.<br>-RULES FOR CHANGES APPLY BY FARE COMPONENT.<br>-IN CASE OF COMBINATION CHARGE THE HIGHEST FEE OF<br> ALL CHANGED FARE COMPONENTS.<br>-WHEN CHANGES ARE MADE NEW FARE AMOUNT FOR THE<br> ENTIRE TICKET SHOULD BE EQUAL OR HIGHER THAN<br> PREVIOUS FARE AMOUNT FOR THE ENTIRE TICKET.<br> FARE AMOUNT - PUBLISHED FARE LEVEL IN CURRENCY OF<br> THE COUNTRY OF COMMENCEMENT OF TRANSPORTATION.<br>-IN CASE OF CHANGES OF A FULLY UNUSED TICKET -<br> CURRENT FARES/TAXES/BSR ON THE DATE OF NEW TICKET<br> ISSUANCE SHOULD BE APPLIED FOR ALL SEGMENTS.<br>-IN CASE OF CHANGES OF A FULLY UNUSED TICKET -<br> IF FARE AMOUNT AND TAXES /IN CURRENCY OF COUNTRY<br> OF COMMENCEMENT OF TRANSPORTATION/ REMAIN THE<br> SAME AND BSR HAS BEEN CHANGED - ONLY TAXES SHOULD<br> BE REPRICED USING BSR ON THE DATE OF NEW TICKET<br> ISSUANCE.<br>-IN CASE OF CHANGES OF A PARTIALLY USED TICKET -<br> HISTORICAL FARES/TAXES/BSR ON THE DATE OF<br> ORIGINAL TICKET ISSUANCE SHOULD BE APPLIED FOR<br> ALL SEGMENTS.<br>-S7 YQ COMPENSATION TAX SHOULD BE ADDITIONALLY<br> COLLECTED FOR ALL NON-SUBSIDY /INCLUDING<br> UNCHANGED AND USED/ SEGMENT/S/ ON THE NEW TICKET<br> EVERY TIME IN CASE OF CHANGES IF THE REISSUE IS<br> PROCESSED IN GDS DIFFERENT FROM S7 TAIS/S7 SMAR -->
                        </div>
                    </div>
            </div>
    </div>
</div>    
</template>

<script setup>
import { ref, inject, onMounted } from 'vue';

const isModalVisible = ref(false)
const segments = ref()
const sections = ref()
const indexItem = ref()
const axios = inject('axios')

const closeModal = () => isModalVisible.value = false

defineExpose({isModalVisible})
onMounted(async ()=>{
    try {
        const response = await axios.get('DataLists');
        segments.value = response.data
        showSection(response.data.PaxSegmentList.PaxSegment[0].PaxSegmentID)
    } catch (error) {
        console.log(error); 
    }
})

const showSection = async (id, index = 0) => {
    indexItem.value = index
    const response = await axios.get('Rules');
    sections.value = response.data.filter(el => el.PaxSegmentRefID === id)
}
</script>

<style lang="scss" scoped>

</style>